# -*- coding: utf-8 -*-
"""part1_grade_tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vp3AzLkkB_Z2otMTnqZQERpkb6TgFa4F
"""

# Task 1: Data Cleaning
# RAW DATA
raw_students = [
    {"name": "  ayesha SHARMA  ", "roll": "101", "marks_str": "88, 72, 95, 60, 78"},
    {"name": "ROHIT verma",       "roll": "102", "marks_str": "55, 68, 49, 72, 61"},
    {"name": "  Priya Nair  ",    "roll": "103", "marks_str": "91, 85, 88, 94, 79"},
    {"name": "karan MEHTA",       "roll": "104", "marks_str": "40, 55, 38, 62, 50"},
    {"name": " Sneha pillai ",    "roll": "105", "marks_str": "75, 80, 70, 68, 85"},
]

# LOOP THROUGH STUDENTS
for student in raw_students:

    # CLEAN NAME
    name = student["name"].strip().title()

    # CONVERT ROLL
    roll = int(student["roll"])

    # CONVERT MARKS
    marks = list(map(int, student["marks_str"].split(", ")))

    # CHECK NAME VALID
    valid = True
    for word in name.split():
        if not word.isalpha():
            valid = False

    if valid:
        print("✓ Valid name")
    else:
        print("✗ Invalid name")

    # PRINT PROFILE
    print("================================")
    print(f"Student : {name}")
    print(f"Roll No : {roll}")
    print(f"Marks   : {marks}")
    print("================================")

# FIND ROLL 103
for student in raw_students:
    if student["roll"] == "103":
        name = student["name"].strip()
        print(name.upper())
        print(name.lower())
# Task 2: Marks Analysis
student_name = "Ayesha Sharma"
subjects     = ["Math", "Physics", "CS", "English", "Chemistry"]
marks        = [88, 72, 95, 60, 78]

# PRINT SUBJECT + GRADE
for i in range(len(subjects)):
    m = marks[i]

    if m >= 90:
        grade = "A+"
    elif m >= 80:
        grade = "A"
    elif m >= 70:
        grade = "B"
    elif m >= 60:
        grade = "C"
    else:
        grade = "F"

    print(subjects[i], "-", m, "-", grade)

# TOTAL & AVERAGE
total = sum(marks)
avg = round(total / len(marks), 2)

print("Total:", total)
print("Average:", avg)

# HIGHEST & LOWEST
max_marks = max(marks)
min_marks = min(marks)

print("Highest:", subjects[marks.index(max_marks)], max_marks)
print("Lowest:", subjects[marks.index(min_marks)], min_marks)

# WHILE LOOP (ADD SUBJECTS)
count = 0

while True:
    sub = input("Enter subject (or done): ")

    if sub.lower() == "done":
        break

    m = input("Enter marks: ")

    if not m.isdigit():
        print("Invalid marks!")
        continue

    m = int(m)

    if m < 0 or m > 100:
        print("Marks must be 0-100")
        continue

    subjects.append(sub)
    marks.append(m)
    count += 1

print("New subjects added:", count)
print("New average:", round(sum(marks)/len(marks),2))
# Task 3: Class Summary
class_data = [
    ("Ayesha Sharma",  [88, 72, 95, 60, 78]),
    ("Rohit Verma",    [55, 68, 49, 72, 61]),
    ("Priya Nair",     [91, 85, 88, 94, 79]),
    ("Karan Mehta",    [40, 55, 38, 62, 50]),
    ("Sneha Pillai",   [75, 80, 70, 68, 85]),
]

print("Name              | Average | Status")
print("----------------------------------------")

pass_count = 0
fail_count = 0
averages = []

for name, marks in class_data:
    avg = round(sum(marks)/len(marks), 2)
    averages.append(avg)

    if avg >= 60:
        status = "Pass"
        pass_count += 1
    else:
        status = "Fail"
        fail_count += 1

    print(f"{name:<18} | {avg:^7} | {status}")

print("Passed:", pass_count)
print("Failed:", fail_count)

# TOPPER
top_avg = max(averages)
topper = class_data[averages.index(top_avg)][0]

print("Topper:", topper, top_avg)

print("Class Average:", round(sum(averages)/len(averages),2))
# Task 4: String Operations
essay = "  python is a versatile language. it supports object oriented, functional, and procedural programming. python is widely used in data science and machine learning.  "

# STEP 1
clean_essay = essay.strip()
print("Clean:", clean_essay)

# STEP 2
print("Title Case:", clean_essay.title())

# STEP 3
print("Count:", clean_essay.count("python"))

# STEP 4
print("Replace:", clean_essay.replace("python", "Python 🐍"))

# STEP 5
sentences = clean_essay.split(". ")
print("List:", sentences)

# STEP 6
for i in range(len(sentences)):
    s = sentences[i]
    if not s.endswith("."):
        s += "."
    print(f"{i+1}. {s}")